### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by joehua87** [buzzcms/buzzcms#1]
## TODO

* [ ] Integrate images with imaginary
* [ ] Dashboard
* [ ] Demo api / dashboard
* [ ] Authentication / Authorization
* [ ] Getting started guide
